/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./player.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // One brand accent (#3ddc97) with a bright hover variant; green-biased
        // charcoal surfaces so chrome and accent share a hue family.
        "on-primary": "#052a1b",
        "surface-container-highest": "#2b332d",
        "primary-container": "#3ddc97",
        "outline-variant": "#2c3630",
        "secondary-fixed": "#80fab8",
        "primary-fixed": "#5cf0b4",
        "error": "#ff6b5e",
        "surface-container-high": "#232a25",
        "timeline-background": "#0d100e",
        "on-secondary-fixed": "#002111",
        "surface-container": "#1d221e",
        "on-surface-variant": "#93a598",
        "surface-container-low": "#171b18",
        "surface": "#111412",
        "secondary-fixed-dim": "#63dd9e",
        "on-primary-container": "#052a1b",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb368",
        "on-tertiary": "#422d00",
        "on-surface": "#e7ece8",
        "primary": "#3ddc97",
        "on-background": "#e7ece8",
        "surface-variant": "#2b332d",
        "secondary-container": "#27573f",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#005232",
        "surface-container-lowest": "#0d100e",
        "surface-bright": "#333c35",
        "on-tertiary-fixed-variant": "#5b4313",
        "on-secondary-container": "#c9f5dd",
        "tertiary-container": "#e1be82",
        "on-tertiary-fixed": "#271900",
        "background": "#111412",
        "tertiary": "#ffb368",
        "secondary": "#63dd9e",
        "on-primary-fixed": "#002112",
        "surface-dim": "#0d100e",
        "error-container": "#93000a",
        "surface-tint": "#5cf0b4",
        "inverse-primary": "#006c45",
        "primary-fixed-dim": "#5cf0b4",
        "tertiary-fixed": "#ffdea8",
        "on-secondary": "#003921",
        "inverse-on-surface": "#2b332d",
        "outline": "#3b463f",
        "on-tertiary-container": "#654c1b",
        "on-primary-fixed-variant": "#005233",
        "inverse-surface": "#e7ece8"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "20px",
        "xxl": "24px",
        "sm": "8px",
        "timeline-h": "192px",
        "md": "12px",
        "xs": "4px",
        "unit": "4px",
        "lg": "16px",
        "sidebar-w": "280px",
        "top-app-bar-h": "56px",
        "stack-gap": "8px",
        "ribbon-height": "120px",
        "gutter": "1px",
        "sidebar-width": "260px",
        "panel-padding": "12px"
      },
      fontFamily: {
        "micro-label": ["Inter"],
        "headline-lg": ["Inter"],
        "editor-mono": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "timeline-label": ["JetBrains Mono"],
        "editor-label-caps": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-sm": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "ribbon-tab": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "label-code": ["JetBrains Mono"]
      },
      fontSize: {
        "micro-label": ["9px", {"lineHeight": "1", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "editor-mono": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "body-lg": ["15px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "timeline-label": ["11px", {"lineHeight": "1", "fontWeight": "400"}],
        "editor-label-caps": ["11px", {"lineHeight": "14px", "letterSpacing": "0.12em", "fontWeight": "500"}],
        "headline-md": ["26px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["12px", {"lineHeight": "18px", "fontWeight": "400"}],
        "headline-sm": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "22px", "fontWeight": "400"}],
        "ribbon-tab": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-code": ["11px", {"lineHeight": "16px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
