/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./player.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#003822",
        "surface-container-highest": "#33343b",
        "primary-container": "#3ddc97",
        "outline-variant": "#3c4a41",
        "secondary-fixed": "#80fab8",
        "primary-fixed": "#65fdb5",
        "error": "#ffb4ab",
        "surface-container-high": "#282a30",
        "timeline-background": "#090b0f",
        "on-secondary-fixed": "#002111",
        "surface-container": "#1d2025",
        "on-surface-variant": "#bbcabe",
        "surface-container-low": "#191b22",
        "surface": "#111319",
        "secondary-fixed-dim": "#63dd9e",
        "on-primary-container": "#005c3a",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#e5c186",
        "on-tertiary": "#422d00",
        "on-surface": "#e2e2eb",
        "primary": "#61f9b1",
        "on-background": "#e2e2eb",
        "surface-variant": "#33343b",
        "secondary-container": "#1ca56b",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#005232",
        "surface-container-lowest": "#0c0e14",
        "surface-bright": "#373940",
        "on-tertiary-fixed-variant": "#5b4313",
        "on-secondary-container": "#00311c",
        "tertiary-container": "#e1be82",
        "on-tertiary-fixed": "#271900",
        "background": "#111319",
        "tertiary": "#ffda9c",
        "secondary": "#63dd9e",
        "on-primary-fixed": "#002112",
        "surface-dim": "#111319",
        "error-container": "#93000a",
        "surface-tint": "#42e09a",
        "inverse-primary": "#006c45",
        "primary-fixed-dim": "#42e09a",
        "tertiary-fixed": "#ffdea8",
        "on-secondary": "#003921",
        "inverse-on-surface": "#2e3037",
        "outline": "#859489",
        "on-tertiary-container": "#654c1b",
        "on-primary-fixed-variant": "#005233",
        "inverse-surface": "#e2e2eb"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "20px",
        "xxl": "24px",
        "sm": "8px",
        "timeline-h": "192px",
        "md": "12px",
        "xs": "4px",
        "unit": "4px",
        "lg": "16px",
        "sidebar-w": "280px",
        "top-app-bar-h": "56px"
      },
      fontFamily: {
        "micro-label": ["Inter"],
        "headline-lg": ["Inter"],
        "editor-mono": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "timeline-label": ["JetBrains Mono"],
        "editor-label-caps": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "micro-label": ["9px", {"lineHeight": "1", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "editor-mono": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "body-lg": ["15px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "timeline-label": ["11px", {"lineHeight": "1", "fontWeight": "400"}],
        "editor-label-caps": ["11px", {"lineHeight": "14px", "letterSpacing": "0.12em", "fontWeight": "500"}],
        "headline-md": ["26px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "1.4", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
